// Importação das fontes Geist e Geist Mono do Google Fonts
import { Geist, Geist_Mono } from "next/font/google";
// Importação dos estilos globais
import "./globals.css";

// Configuração da fonte Geist Sans
const geistSans = Geist({
  variable: "--font-geist-sans",  // Variável CSS para a fonte Geist Sans
  subsets: ["latin"],             // Subconjunto de caracteres latinos
});

// Configuração da fonte Geist Mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",  // Variável CSS para a fonte Geist Mono
  subsets: ["latin"],             // Subconjunto de caracteres latinos
});

// Metadados da aplicação
export const metadata = {
  title: "GestCare",        // Título da aplicação
  description: "Generated by create next app",  // Descrição da aplicação
};

// Componente de layout raiz que envolve toda a aplicação
export default function RootLayout({ children }) {
  return (
    // Estrutura HTML base com idioma definido como inglês
    <html lang="en">
      {/* Corpo da página com as fontes aplicadas e suavização de texto */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Renderização dos componentes filhos */}
        {children}
      </body>
    </html>
  );
}

